name: e_commerce_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0-96.0.dev <4.0.0"
  #----------------- PACKAGES ------------------#
dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.8
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.0
  flutter_native_splash: ^2.3.10
  geocoding: ^3.0.0
  geolocator: ^10.1.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  iconsax: ^0.0.8
  image_picker: ^1.0.8
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  latlong2: ^0.9.1
  lottie: ^3.1.0
  package_info: ^2.0.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  #----------------- LOCAL ASSETS ---------------#
  assets:
    - assets/images/animations/
    - assets/images/compte/
    - assets/images/home/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/logos/

  #----------------- LOCAL ASSETS ---------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
